-- DAR-346: DAR 분류 확대 — event-classifier OTHER 4225 축소
-- 라이브 DisclosureEvent eventType=OTHER 상위 reportName 패턴(전수조사) 기반 신규 분류 타입 18종.
-- 가산형(ADD VALUE) 마이그레이션. PostgreSQL enum 값 추가는 비파괴적이며 기존 row에 영향 없음.
-- 적용(prisma migrate deploy)은 사용자/운영 승인 후 수행. 적용 후 OTHER 이벤트 reprocess 시 재분류된다.
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'INSIDER_TRADING_REPORT';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'SECURITIES_OFFERING';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'PERIODIC_DISCLOSURE';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'SHAREHOLDER_MEETING';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'IR_EVENT';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'RELATED_PARTY_TRANSACTION';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'AFFILIATE_GROUP_DISCLOSURE';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'OWNERSHIP_DISCLOSURE';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'DEBT_GUARANTEE';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'CAPITAL_REDUCTION';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'BONUS_ISSUE';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'MERGER_SPLIT';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'INVESTMENT_DECISION';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'STOCK_OPTION';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'EXECUTIVE_CHANGE';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'INQUIRY_DISCLOSURE';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'MARKET_NOTICE';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'CONVERTIBLE_EXERCISE';
